/// Generate shell aliases to stdout.
///
/// This outputs a complete shell script that can be sourced from .zshrc / .bashrc.
/// It does NOT write to any file — callers pipe or redirect as needed.
pub fn generate_aliases() -> String {
    ALIASES_SCRIPT.to_string()
}

static ALIASES_SCRIPT: &str = r#"#!/bin/sh
# Generated by forge — do not edit manually
# Regenerate with: forge shell generate-aliases

# General
alias cic='set completion-ignore-case On'
alias ll='ls -alh'
alias lc='colorls -a -l --dark --gs'
alias le='exa -alh -t modified --group-directories-first --git --tree --level=2 --color-scale --color=always'

# Kubernetes
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgd='kubectl get deployments'
alias klf='kubectl logs -f'

# Ruby/Bundler
alias bi='bundle install'
alias bu='bundle update'
alias brake='bundle exec rake'
alias be='bundle exec'

# SSH
alias addkey='eval $(ssh-agent) && ssh-add'

# File/Directory
alias dirsizes='du -sch ./*'
alias numFiles='echo $(ls -1 | wc -l)'
alias qfind='find . -name '
alias editHosts='sudo ${EDITOR:-vim} /etc/hosts'

# System
alias cpuHogs='ps wwaxr -o pid,stat,%cpu,time,command | head -10'
alias usedNetPorts='lsof -i'
alias myip='curl -s checkip.dyndns.org | sed -e '\''s/.*Current IP Address: //'\'' -e '\''s/<.*$//'\'''

# macOS-specific
if [ "$(uname)" = "Darwin" ]; then
  alias flushDNS='sudo killall -HUP mDNSResponder && dscacheutil -flushcache'
fi
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_aliases_not_empty() {
        let output = generate_aliases();
        assert!(!output.is_empty());
    }

    #[test]
    fn test_generate_aliases_contains_key_aliases() {
        let output = generate_aliases();
        assert!(output.contains("alias ll="));
        assert!(output.contains("alias k="));
        assert!(output.contains("alias addkey="));
        assert!(output.contains("flushDNS"));
    }

    #[test]
    fn test_generate_aliases_has_header() {
        let output = generate_aliases();
        assert!(output.starts_with("#!/bin/sh"));
        assert!(output.contains("Generated by forge"));
    }
}
